name: Automated Build & Deploy

on:
  workflow_dispatch:
  
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install missing programs
      run: |
        pip3 install virtualenv
        gem install bundler

    - name: Prepare the build environment
      run: ./prepare.sh

    - name: Build the Webpage
      run: |
        source .venv/bin/activate
        cd ./webroot
        PATH=../:$PATH pelican content -s publishconf.py

    - name: Populate SSH credentials
      shell: bash
      env:
        SSH_SECRET_KEY: ${{ secrets.SSH_SECRET_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_SECRET_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

    - name: Deploy the webpage
      shell: bash
      env:
        SSH_USER: ${{ secrets.ASSET_SYNC_USERNAME }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: rsync -ac --delete -e 'ssh -p "$SSH_PORT" -l "$SSH_USER"' output/ testing.ikbk.net:/srv/http/
