name: Automated Build & Deploy

on:
  workflow_dispatch:
  
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install missing programs
      run: |
        pip3 install virtualenv
        gem install bundler

    - name: Prepare the build environment
      run: ./prepare.sh

    - name: Build the Webpage
      run: |
        source .venv/bin/activate
        cd ./webroot
        PATH=../:$PATH pelican content -s publishconf.py
