= Unity 2018.3 で追加された新機能

:date:2018-12-18 23:45
:tags: Unity, games, programming, technical
:category: 技術系
:summary: Unity 2018.3 の新機能で気になったものを紹介

これは https://adventar.org/calendars/3131[KMCアドベントカレンダー2018]の18日目の記事です！！

== 寒いですね！
こんにちは。ikubakuです。それにしても最近すごく寒いですね！年末で忙しい方も多いと思いますが、暖かくして過ごしてください。

今回は最近リリースされたUnity 2018.3の新機能で、個人的に気になったものを紹介していこうと思います。

== Unity 2018.3リリース
Unityは、Unity Technologyが開発しているゲーム開発支援ツールおよびそのゲームエンジンです。市販のゲームを始め、個人や同人チームが制作したゲームで幅広く使われています。Unityは最近から（元から？）、年に3回ほど大きな更新が行われるようになっているようです。そのたびに開発を容易にしたり、ゲームを楽しく快適にする機能がどんどん追加されているようです。そんなわけで、つい最近リリースされたバージョン2018.3で追加された機能を見てみることにしました。（実は私も時々使うけれど、これまでほとんどアップデートの情報を見ていなかったことは秘密）

== アップデートで気になったもの一覧
今回のアップデートでも、様々な変更や追加機能があったようです。全部紹介したいところですが、そんなことをすると私のMPが尽きてしまって年末頑張れないので、私が特に気になったものだけ紹介したいと思います。以下にそれらの項目を挙げます。

* Physical Cameras
* Project Tiny Preview
* C# 7.3/.NET Framework 4.xサポート
* GC Global Enable/Disable
* Isometric Tile Maps
* Prefabの機能更新

ではここからは、それらについて詳しかったり詳しくなかったりする解説をしていきます。

=== Physical Cameras
これは、UnityのCameraオブジェクトに対する機能追加です。これまでは言ってみれば、カメラワークができる抽象的なカメラ、でしかなかったのですが、今回のアップデートでレンズの焦点距離や、イメージセンササイズなどの物理的なパラメータが指定できるようになりました。これによって、レンズフレアなどの物理的な現象が再現できるようになるそうです。

=== Project Tiny Preview
Project Tinyは軽量なゲームを作るためのUnityのエディター及びエンジンのモードで、今の所簡単な2Dゲームやゲームができる広告（Google Doodleみたいなもの？）を作るのに使えるそうです。 https://unity.com/ja/solutions/instant-games/2d-games-and-playables[Unityでの紹介サイト]によれば、ゲーム自体のサイズは約2MBほどです。私もUnityでブラウザをターゲットにしたゲームを作成したことがありますが、それのサイズ(20MB)に比べればかなり小さいです。携帯端末で表示するWebページで使いたい時に便利になるかもしれません。この機能を使うには別途Package Managerから導入する必要があります。

== C# 7.3/.NET Framework 4.xサポート

== 参考
* https://blogs.unity3d.com/jp/2018/12/13/introducing-unity-2018-3/[Introducing Unity 2018.3]

